[tool.bandit]
skips = ["B101", "B311"]

[tool.coverage.report]
fail_under = 100
omit = [
    "*/migrations/*",
]
show_missing = true
skip_covered = true

[tool.isort]
profile = "black"
src_paths = ["readlits"]

[tool.pytest.ini_options]
addopts = "--no-migrations --disable-socket"
DJANGO_SETTINGS_MODULE = "project.testing_settings"
filterwarnings = [
    "error",
]
testpaths = [
    "readlits",
]
