name: Tests Runner
on:
  - push
  - pull_request

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-22.04
    env:
      ALLOWED_HOSTS: '*'
      SECRET_KEY: ${{secrets.SECRET_KEY}}

    steps:
      - name: Get the app source code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: 'requirements*.txt'

      - name: Install Python packages
        run: pip install -r requirements.txt -r requirements-dev.txt

      - name: Collect static file
        run: python manage.py collectstatic

      - name: Test it
        run: make coverage
